name: tests

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          path: master
          
      - name: Checkout new
        uses: actions/checkout@v4
        with:
          ref: new-tests
          path: new

      - name: print source
        run: echo ${{GITHUB_HEAD_REF}}
      
      
        
