name: tests

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          path: master
          
      - name: Checkout new
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: new
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Run new branch
        run: cd new; gradle test clean

      - name: Setup running old on old Code
        run: |
         cd new
         sed -i '/repositories {/i sourceSets {\n  main {\n    java {\n      srcDirs = ["/home/runner/work/mars-rover-kata-java/mars-rover-kata-java/master/src/"]\n    }\n    resources {\n      srcDirs = ["/home/runner/work/mars-rover-kata-java/mars-rover-kata-java/master/resources"]\n    }\n  }\n}' build.gradle

      - name: Check gradle file
        run: cd new; cat build.gradle
        
      - name: Check source Code
        run: cd master/src/main/java/
      
        
      - name: Run new branch tests on master
        run: cd new; gradle test --rerun-tasks --no-build-cache

      
