name: prettier-check

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          path: master
          
      - name: Checkout new
        uses: actions/checkout@v4
        with:
          ref: $ {{ github.ref }}
          path: new

      
      
        
