name: tests

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          path: master
          
      - name: Checkout new
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: new
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Runs old tests
        run: cd new | ls 
      
