name: tests

on:
  pull_request:
    branches: ["master"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4
        with:
          path: master
          
      - name: Checkout new
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          path: new
          
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 8

      - name: Run new branch
        run: cd new; gradle test

      - name: Setup running old on old Code
        run: |
         cd new
         echo 'sourceSets {
            main {
              java {
                srcDirs = ["/home/runner/work/mars-rover-kata-java/mars-rover-kata-java/master/src/main/java"]
              }
              resources {
                srcDirs = ["/home/runner/work/mars-rover-kata-java/mars-rover-kata-java/master/src/main/resources"]
              }
            }
          }' | sed -i '/repositories {/i sourceSets {\n  main {\n    java {\n      srcDirs = ["src/main/java"]\n    }\n    resources {\n      srcDirs = ["src/main/resources"]\n    }\n  }\n}' build.gradle
          
      - name: Run new branch on master
        run: cd new; gradle test

      
